# Enter your code here. Read input from STDIN. Print output to STDOUT
n=int(input())
# print(n)
s=set(map(int,input().split()))
# print(s)
m=int(input())
# print(m)
t=set(map(int,input().split()))
# print(t)
z=s.difference(t)
# print(z)
print(len(z))
